### ISSUE TITLE
[OPENGL] Crash when attempting to change sRGB to AppleD3 in Right Click View options

### ISSUE THREAD

**Issue by Corruptinator** [sobotka/olive#13]
**Platform**
Windows 10 Pro 64-bit (Custom PC) Ryzen 9 3900x, Nvidia RTX 2080 Super

**Summary**
After right clicking on the video output view I have the options to change the view to sRGB or change the contrast, sometimes when I attempt to click one of the options such as sRGB it would freeze then crash.

**Comment by itsmattkc** [comment]
I've so far been unable to recreate this, what OCIO config were you using?

**Comment by Corruptinator** [comment]
https://github.com/sobotka/filmic-blender

**Comment by sobotka** [comment]
The Olive branch is the appropriate one for the test footage. https://github.com/sobotka/filmic-blender/tree/olive-configuration

**Comment by itsmattkc** [comment]
If you check c74134b5b04e97adb2099c16041c415aa62a2231, Olive will catch the exception and show a messagebox rather than crashing.

However I don't get any issue switching to D3, but I get the following error message switching to BT.1886. Do you know what it means @sobotka?

![image](https://user-images.githubusercontent.com/34096995/74588891-85c55b00-5054-11ea-8c74-4972e588ff90.png)

**Comment by sobotka** [comment]
Locale error?

https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/297

**Comment by itsmattkc** [comment]
Fixed in 69e65f6784a002377bf7ef3c19fb5d3b4b5d848d. A somewhat cryptic error from OCIO for an Olive flaw where it wouldn't check whether the current view still existed when a new display was being set. In the Filmic config, the "sRGB" and "Apple Display P3" displays both have an "sRGB OETF" view, but "BT.1886" doesn't and since Olive didn't check, it would attempt to make a BT.1886/sRGB OETF processor regardless, hence this bug.

**Comment by sobotka** [comment]
Can you post the error you saw and I’ll push it upstream for more clarity, if it is different from the above pop up?

**Comment by itsmattkc** [comment]
Yeah the message in the dialog (`DisplayTransform error` onwards), seemingly the only feedback I could get from OCIO
