### ISSUE TITLE
[CACHE] Inserting a Generator-Solid drops cache

### ISSUE THREAD

**Issue by sobotka** [sobotka/olive#39]
**Platform**
Debian Buster amd64

**Summary**
Inserting a Generator -> Solid drops the cache and removes the UI entity from the Timeline.

**Additional Information / Output**
1. Load a piece of footage.
2. Add a Generator -> Solid and drag it between the Clip and Track
3. Profit

Also note that the parameters for the Solid do not reveal the UI interaction swatch, as well as apparently dropping the OpenColorIO configuration.

**Comment by itsmattkc** [comment]
Not technically a bug, disconnecting the clip would remove it from the timeline as you describe. You'd want to connect the solid to the clip's input rather than the track's.

**Comment by Simran-B** [comment]
I guess it should be disallowed to connect it to a track node?

**Comment by itsmattkc** [comment]
Not necessarily, the nodes don't pass around single values, i.e. they're not either "compatible" or "incompatible". They pass around tables so that nodes only take/alter the values they need but can continue passing other values on to later nodes. It's therefore not up to the program to decide whether a whole table of values can be plugged into a node or not.

**Comment by Simran-B** [comment]
I see. Such nodes should simply passthru the data without even looking at it, but what causes the crash? Or is it fixed?

**Comment by sobotka** [comment]
> but what causes the crash? 

It doesn’t crash. It disappears from the Timeline because each timeline entity requires a Clip wrapper.
